### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bokkenka** [wynand1004/Projects#2]
How many suggestions do you want?

-- Power-ups...
-- -- Shields
-- -- Multi-bullets...
-- -- -- Two-way: front and back
-- -- -- Three-way: front and sides
-- -- -- Four-way: front, back, and sides
-- -- Health
-- -- Each could be a different color

-- Should be refactored into multiple files...
-- -- Pretty much one for each class.
-- -- Everything else in space_arena.py.

-- The bounce function can be way shorter:
```
    def bounce(self, other):
        self.dx, self.dy, other.dx, other.dy = other.dx, self.dx, self.dx, self.dy
```
-- -- Can be split into two lines (one for x and one for y) if you want.

**Comment by wynand1004** [comment]
Hey - thanks for the suggestions!

Powerups are already implemented but I want to increase the number/type. 
Shields sound cool as well - will look into it.
Multibullets - that would be an awesome powerup. Will definitely give that a shot (if I don't forget).
The player and all the enemies already have health.

I definitely want to completely refactor the game, but for testing I'll keep it as one file to make it easy to download and test.

I know the bounce can be shortened - it's a nice python feature, but since I also teach Java I want my students to understand how these things are done step by step.

Thanks again for the great suggestions!

**Comment by wynand1004** [comment]
Check out the latest preview - I've added multiple missiles shooting. I've already implemented health. No shields yet though - may pass on that one. We'll see!
